### ISSUE TITLE
worker failed to start with epoll.node error

### ISSUE THREAD

**Issue by terryg** [metatooth/herbert#35]
<pre><font color="#4E9A06"><b>herbert@emerald</b></font>:<font color="#3465A4"><b>~/herbert $</b></font> sudo /usr/bin/node dist/worker/main.js
/home/herbert/herbert/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: /home/herbert/herbert/node_modules/epoll/build/Release/epoll.node: file too short
<font color="#555753">    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18)</font>
<font color="#555753">    at Module.load (internal/modules/cjs/loader.js:937:32)</font>
<font color="#555753">    at Function.Module._load (internal/modules/cjs/loader.js:778:12)</font>
<font color="#555753">    at Module.require (internal/modules/cjs/loader.js:961:19)</font>
<font color="#555753">    at require (internal/modules/cjs/helpers.js:92:18)</font>
    at bindings (/home/herbert/herbert/node_modules/<u style="text-decoration-style:single">bindings</u>/bindings.js:112:48)
    at /home/herbert/herbert/node_modules/<u style="text-decoration-style:single">epoll</u>/epoll.js:7:31
    at Object.&lt;anonymous&gt; (/home/herbert/herbert/node_modules/<u style="text-decoration-style:single">epoll</u>/epoll.js:15:3)
<font color="#555753">    at Module._compile (internal/modules/cjs/loader.js:1072:14)</font>
<font color="#555753">    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)</font>
</pre>

**Comment by terryg** [comment]
worksforme
